export interface ProjectConfig {
  name: string;
  repo: string;
  hasCI: boolean;
  stack: 'nextjs' | 'fastify' | 'astro' | 'dotnet' | 'node' | 'unknown';
  hasQodo: boolean;
  hasClaude: boolean;
  hasSelfHealing: boolean;
  hasHusky: boolean;
  hasRenovate: boolean;
  hasGitleaks: boolean;
  hasLighthouse: boolean;
  hasLinkChecker: boolean;
  vercel: boolean;
  productionUrl?: string;
  testFramework?: 'vitest' | 'xunit' | 'jest' | 'none';
  hasTests?: boolean;
}

export interface CoverageThresholds {
  services: number;
  global: number;
  ratchet: boolean;
}

export interface ClaudeReviewConfig {
  maxReviewsPerDay: number;
  enabledRepos: string[];
  model: string;
}

export const COVERAGE_THRESHOLDS: CoverageThresholds = {
  services: 80,
  global: 60,
  ratchet: true,
};

export const CLAUDE_REVIEW_CONFIG: ClaudeReviewConfig = {
  maxReviewsPerDay: 20,
  enabledRepos: [
    'thonyAGP/Email_Assistant',
    'thonyAGP/CasaSync',
    'thonyAGP/livret-au-marais',
    'thonyAGP/au-marais',
    'thonyAGP/ClubMedRoomAssignment',
    'thonyAGP/lecteur-magic',
  ],
  model: 'claude-sonnet-4-5-20250929',
};

export const QUALITY_WEIGHTS = {
  ciPasses: 20,
  coverageAboveThreshold: 20,
  prettierClean: 10,
  eslintZeroWarnings: 15,
  branchProtection: 10,
  depsUpToDate: 10,
  noSecrets: 15,
} as const;

export const KNOWN_PROJECTS: ProjectConfig[] = [
  {
    name: 'Email_Assistant',
    repo: 'thonyAGP/Email_Assistant',
    hasCI: true,
    stack: 'fastify',
    hasQodo: true,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: true,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: true,
  },
  {
    name: 'ClubMedRoomAssignment',
    repo: 'thonyAGP/ClubMedRoomAssignment',
    hasCI: true,
    stack: 'dotnet',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: true,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'CasaSync',
    repo: 'thonyAGP/CasaSync',
    hasCI: true,
    stack: 'nextjs',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'Livret_accueil_Au-Marais',
    repo: 'thonyAGP/livret-au-marais',
    hasCI: true,
    stack: 'nextjs',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: true,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: true,
  },
  {
    name: 'Site_Au-marais',
    repo: 'thonyAGP/au-marais',
    hasCI: true,
    stack: 'nextjs',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: true,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: true,
    productionUrl: 'https://au-marais.fr',
  },
  {
    name: 'Lecteur_Magic',
    repo: 'thonyAGP/lecteur-magic',
    hasCI: true,
    stack: 'node',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'API_Claude',
    repo: 'thonyAGP/claude-cli-wrapper',
    hasCI: false,
    stack: 'node',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'MCP_Quota_Claude',
    repo: 'thonyAGP/MCP_Quota_Claude',
    hasCI: false,
    stack: 'node',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'Statusline',
    repo: 'thonyAGP/statusline',
    hasCI: false,
    stack: 'node',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'Site_Greg-Assainissement',
    repo: 'thonyAGP/Site_Greg-Assainissement',
    hasCI: false,
    stack: 'nextjs',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'Site_1970_Plomberie',
    repo: 'thonyAGP/Site_1970_Plomberie',
    hasCI: false,
    stack: 'astro',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'Thumbfast_createur_images',
    repo: 'thonyAGP/Thumbfast',
    hasCI: false,
    stack: 'nextjs',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'Utilitaire_Webapp',
    repo: 'thonyAGP/Utilitaire_Webapp',
    hasCI: false,
    stack: 'nextjs',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'Site_Soraya',
    repo: 'thonyAGP/Site-Soraya',
    hasCI: false,
    stack: 'unknown',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'Benchmark_Claude',
    repo: 'thonyAGP/Benchmark_Claude',
    hasCI: false,
    stack: 'unknown',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'test_codingmenace',
    repo: 'thonyAGP/test_codingmenace',
    hasCI: false,
    stack: 'nextjs',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'RemoteDevDashboard',
    repo: 'thonyAGP/RemoteDevDashboard',
    hasCI: false,
    stack: 'unknown',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'ClaudePilot',
    repo: 'thonyAGP/ClaudePilot',
    hasCI: false,
    stack: 'unknown',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'Lanceur_Claude',
    repo: 'thonyAGP/claude-launcher',
    hasCI: false,
    stack: 'unknown',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'analyse-negocio',
    repo: 'thonyAGP/analyse-negocio',
    hasCI: false,
    stack: 'unknown',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
  {
    name: 'SqlConnectionTest',
    repo: 'thonyAGP/SqlConnectionTest',
    hasCI: false,
    stack: 'dotnet',
    hasQodo: false,
    hasClaude: false,
    hasSelfHealing: false,
    hasHusky: false,
    hasRenovate: false,
    hasGitleaks: false,
    hasLighthouse: false,
    hasLinkChecker: false,
    vercel: false,
  },
];

export const GITHUB_OWNER = 'thonyAGP';

export const DASHBOARD_URL = 'https://thonyagp.github.io/DevOps-Factory/';

export const SCAN_CONFIG = {
  cronIntervalHours: 6,
  dashboardRefreshHours: 4,
  ignoredRepos: ['DevOps-Factory', 'Parametrage_Claude', 'Migration_Pc1_vers_Pc2', '.github'],
  requiredFiles: {
    node: ['package.json'],
    dotnet: ['*.csproj', '*.sln'],
  },
  workflowFiles: {
    ci: 'ci.yml',
    claudeReview: 'claude-review.yml',
    selfHealing: 'self-healing.yml',
    qodoMerge: 'qodo-merge.yml',
    gitleaks: 'gitleaks.yml',
    lighthouse: 'lighthouse.yml',
    linkChecker: 'link-checker.yml',
  },
  productionUrls: [
    { name: 'Site_Au-marais', url: 'https://au-marais.fr' },
    { name: 'Livret_accueil_Au-Marais', url: 'https://livret.au-marais.fr' },
  ],
};
