import { execSync } from 'node:child_process';
import { writeFileSync, readFileSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { sh as _sh, tmpDir } from '../shell-utils.js';
import { configureGitAuth } from './git-operations.js';
import { ensureLabel, isDuplicateFix } from './pr-management.js';

const sh = (cmd: string, timeout = 60_000) => _sh(cmd, { timeout });

export const fixLockfileIssues = (
  repo: string,
  runId: string,
  defaultBranch: string
): string | null => {
  const workDir = `${tmpDir}/self-heal-lockfile-${Date.now()}`.replace(/\\/g, '/');

  const git = (cmd: string) =>
    execSync(cmd, { cwd: workDir, encoding: 'utf-8', timeout: 60_000, stdio: 'pipe' }).trim();

  try {
    console.log(`  Cloning ${repo}...`);
    execSync(`gh repo clone ${repo} "${workDir}" -- --depth 1`, {
      encoding: 'utf-8',
      timeout: 120_000,
      stdio: 'pipe',
    });

    const pm = existsSync(`${workDir}/pnpm-lock.yaml`)
      ? 'pnpm'
      : existsSync(`${workDir}/yarn.lock`)
        ? 'yarn'
        : 'npm';

    console.log(`  Detected package manager: ${pm}`);

    console.log('  Installing dependencies to update lockfile...');
    const installCmd =
      pm === 'pnpm'
        ? 'pnpm install --ignore-scripts'
        : pm === 'yarn'
          ? 'yarn install --ignore-scripts'
          : 'npm install --ignore-scripts';

    try {
      execSync(installCmd, {
        cwd: workDir,
        encoding: 'utf-8',
        timeout: 120_000,
        stdio: 'pipe',
        maxBuffer: 10 * 1024 * 1024,
      });
    } catch {
      console.log('  Install failed but continuing - lockfile may still be updated');
    }

    let changed: string;
    try {
      changed = execSync('git diff --name-only', {
        cwd: workDir,
        encoding: 'utf-8',
        stdio: 'pipe',
      }).trim();
    } catch {
      changed = '';
    }

    if (!changed) {
      console.log('  No lockfile changes');
      return null;
    }

    const fileCount = changed.split('\n').filter(Boolean).length;
    console.log(`  ${fileCount} file(s) updated`);

    const branch = `ai-fix/lockfile-${Date.now()}`;
    git('git config user.name "DevOps Factory Bot"');
    git('git config user.email "devops-factory[bot]@users.noreply.github.com"');
    configureGitAuth(workDir, repo);
    git(`git checkout -b ${branch}`);
    git('git add -A');
    git(
      `git commit -m "chore: update ${pm === 'pnpm' ? 'pnpm' : pm === 'yarn' ? 'yarn' : 'npm'} lockfile (${fileCount} files)"`
    );

    console.log(`  Pushing ${branch}...`);
    execSync(`git push origin ${branch}`, {
      cwd: workDir,
      encoding: 'utf-8',
      timeout: 120_000,
      stdio: 'pipe',
    });

    if (isDuplicateFix(repo, 'lockfile')) {
      console.log('  [DEDUP] Skipping duplicate fix - lockfile PR already closed recently');
      return null;
    }

    ensureLabel(repo, 'ai-fix', '7057ff', 'Auto-generated fix by DevOps Factory');

    const body = [
      `## ${pm.toUpperCase()} Lockfile Update`,
      '',
      `**Failed Run**: https://github.com/${repo}/actions/runs/${runId}`,
      '**Generated by**: DevOps Factory Self-Healing',
      '',
      `Auto-updated lockfile in **${fileCount} file(s)** using \`${installCmd}\`.`,
      '',
      '---',
      '> This PR was automatically generated to fix lockfile consistency issues.',
    ].join('\n');

    const bodyFile = `${tmpDir}/pr-body.md`;
    writeFileSync(bodyFile, body);

    const prUrl = sh(
      `gh pr create --repo ${repo} --head ${branch} --base ${defaultBranch} --title "chore: update ${pm} lockfile (${fileCount} files)" --body-file "${bodyFile}" --label "ai-fix"`
    );

    return prUrl.match(/(https:\/\/[^\s]+)/)?.[1] || prUrl;
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error(`  Lockfile fix failed: ${msg.slice(0, 300)}`);
    return null;
  } finally {
    try {
      rmSync(workDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }
};

export const fixPrettierIssues = (
  repo: string,
  runId: string,
  defaultBranch: string
): string | null => {
  const localTmpDir = `${tmpDir}/self-heal-prettier-${Date.now()}`.replace(/\\/g, '/');

  const git = (cmd: string) =>
    execSync(cmd, { cwd: localTmpDir, encoding: 'utf-8', timeout: 60_000, stdio: 'pipe' }).trim();

  try {
    console.log(`  Cloning ${repo}...`);
    execSync(`gh repo clone ${repo} "${localTmpDir}" -- --depth 1`, {
      encoding: 'utf-8',
      timeout: 120_000,
      stdio: 'pipe',
    });

    const prettierConfigs = [
      '.prettierrc',
      '.prettierrc.json',
      '.prettierrc.yml',
      '.prettierrc.js',
      'prettier.config.js',
      'prettier.config.mjs',
    ];

    const hasPrettierIn = (dir: string): boolean => {
      if (prettierConfigs.some((f) => existsSync(`${dir}/${f}`))) return true;
      try {
        const pkg = JSON.parse(readFileSync(`${dir}/package.json`, 'utf-8'));
        return !!pkg.prettier || !!pkg.devDependencies?.prettier || !!pkg.dependencies?.prettier;
      } catch {
        return false;
      }
    };

    let workDir = '';

    if (hasPrettierIn(localTmpDir)) {
      workDir = localTmpDir;
    } else {
      const entries = readdirSync(localTmpDir, { withFileTypes: true })
        .filter((d) => d.isDirectory() && !d.name.startsWith('.') && d.name !== 'node_modules')
        .map((d) => d.name);

      for (const entry of entries) {
        const subDir = `${localTmpDir}/${entry}`;
        if (hasPrettierIn(subDir)) {
          workDir = subDir;
          break;
        }
      }
    }

    if (!workDir) {
      console.log('  No Prettier config found - skipping');
      return null;
    }

    const relDir = workDir === localTmpDir ? '(root)' : workDir.split('/').pop() + '/';
    console.log(`  Prettier config found in: ${relDir}`);

    console.log('  Installing dependencies...');
    const pm = existsSync(`${workDir}/pnpm-lock.yaml`)
      ? 'pnpm'
      : existsSync(`${workDir}/yarn.lock`)
        ? 'yarn'
        : 'npm';

    const install = (cmd: string): boolean => {
      try {
        execSync(cmd, { cwd: workDir, encoding: 'utf-8', timeout: 120_000, stdio: 'pipe' });
        return true;
      } catch {
        return false;
      }
    };

    const frozen =
      pm === 'pnpm'
        ? 'pnpm install --frozen-lockfile --ignore-scripts'
        : pm === 'yarn'
          ? 'yarn install --frozen-lockfile --ignore-scripts'
          : 'npm ci --ignore-scripts';

    if (!install(frozen)) {
      const loose =
        pm === 'pnpm'
          ? 'pnpm install --ignore-scripts'
          : pm === 'yarn'
            ? 'yarn install --ignore-scripts'
            : 'npm install --ignore-scripts';
      install(loose);
    }

    console.log('  Running prettier --write...');
    try {
      execSync(
        'npx prettier --write "**/*.{ts,tsx,js,jsx,json,css,md,yml,yaml}" --ignore-unknown',
        {
          cwd: workDir,
          encoding: 'utf-8',
          timeout: 120_000,
          stdio: 'pipe',
          maxBuffer: 10 * 1024 * 1024,
        }
      );
    } catch {
      /* prettier may exit non-zero on parse errors but still format valid files */
    }

    let changed: string;
    try {
      changed = execSync('git diff --name-only', {
        cwd: localTmpDir,
        encoding: 'utf-8',
        stdio: 'pipe',
      }).trim();
    } catch {
      changed = '';
    }

    if (!changed) {
      console.log('  No formatting changes');
      return null;
    }

    const fileCount = changed.split('\n').filter(Boolean).length;
    console.log(`  ${fileCount} file(s) reformatted`);

    const branch = `ai-fix/prettier-${Date.now()}`;
    git('git config user.name "DevOps Factory Bot"');
    git('git config user.email "devops-factory[bot]@users.noreply.github.com"');

    configureGitAuth(localTmpDir, repo);

    git(`git checkout -b ${branch}`);
    git('git add -A');
    git(`git commit -m "style: auto-fix formatting with Prettier (${fileCount} files)"`);

    console.log(`  Pushing ${branch}...`);
    execSync(`git push origin ${branch}`, {
      cwd: localTmpDir,
      encoding: 'utf-8',
      timeout: 120_000,
      stdio: 'pipe',
    });

    if (isDuplicateFix(repo, 'Prettier')) {
      console.log('  [DEDUP] Skipping duplicate fix - Prettier PR already closed recently');
      return null;
    }

    ensureLabel(repo, 'ai-fix', '7057ff', 'Auto-generated fix by DevOps Factory');

    const body = [
      '## Prettier Formatting Fix',
      '',
      `**Failed Run**: https://github.com/${repo}/actions/runs/${runId}`,
      '**Generated by**: DevOps Factory Self-Healing',
      '',
      `Auto-fixed formatting in **${fileCount} file(s)** using Prettier.`,
      '',
      '---',
      '> This PR was automatically generated. No functional changes - formatting only.',
    ].join('\n');

    const bodyFile = `${tmpDir}/pr-body.md`;
    writeFileSync(bodyFile, body);

    const prUrl = sh(
      `gh pr create --repo ${repo} --head ${branch} --base ${defaultBranch} --title "style: auto-fix Prettier formatting (${fileCount} files)" --body-file "${bodyFile}" --label "ai-fix"`
    );

    return prUrl.match(/(https:\/\/[^\s]+)/)?.[1] || prUrl;
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error(`  Prettier fix failed: ${msg.slice(0, 300)}`);
    return null;
  } finally {
    try {
      rmSync(localTmpDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }
};
