import { writeFileSync, unlinkSync } from 'node:fs';
import { KNOWN_PROJECTS } from '../../factory.config.js';
import { notify } from '../notify.js';
import { sh as _sh, tmpDir } from '../shell-utils.js';
import {
  DEDUP_WINDOW_HOURS,
  AUTO_MERGE_CONFIDENCE_THRESHOLD,
  AUTO_MERGE_GRADUATED_THRESHOLD,
} from './constants.js';
import { matchedPatternConfidence } from './pattern-db.js';

const sh = (cmd: string, timeout = 60_000) => _sh(cmd, { timeout });

export const ensureLabel = (
  repo: string,
  label: string,
  color: string,
  description: string
): void => {
  sh(
    `gh api "repos/${repo}/labels" -X POST -f name="${label}" -f color="${color}" -f description="${description}"`
  );
};

export const getHealingState = (
  repo: string
): 'discovered' | 'monitored' | 'healing_supervised' | 'healing_graduated' | 'paused' => {
  const project = KNOWN_PROJECTS.find((p) => p.repo === repo);
  return project?.healingState ?? 'healing_supervised';
};

export const createFixPR = (
  repo: string,
  branch: string,
  baseBranch: string,
  runId: string,
  explanation: string,
  patternId?: string,
  aiProvider?: string,
  patternSignature?: string
): string => {
  const title = patternId ? `fix: CI fix [pattern:${patternId}]` : 'fix: AI-generated CI fix';
  const source = patternId ? `Pattern DB (${patternId})` : 'AI analysis';
  const confidence = patternId ? matchedPatternConfidence(patternId) : 0;
  const healingState = getHealingState(repo);

  const body = `## Auto-Generated CI Fix

**Failed Run**: https://github.com/${repo}/actions/runs/${runId}
**Generated by**: DevOps Factory Self-Healing
**Source**: ${source}
${patternId ? `**Pattern ID**: \`${patternId}\`\n**Confidence**: ${(confidence * 100).toFixed(0)}%` : ''}
${patternSignature ? `**Signature**: \`${patternSignature.slice(0, 120)}\`` : ''}
${aiProvider ? `**AI Model**: ${aiProvider}` : ''}
**Repo State**: \`${healingState}\`

### Why this fix?
The CI pipeline failed on run [#${runId}](https://github.com/${repo}/actions/runs/${runId}).
${patternId ? `Pattern \`${patternId}\` matched with ${(confidence * 100).toFixed(0)}% confidence.` : 'No known pattern matched — an AI model analyzed the failure logs.'}

### Analysis
${explanation}

---
> This PR was automatically generated. Please review carefully before merging.
> If this fix is wrong, close the PR and add the label \`fix-rejected\` to improve future accuracy.
> Label: \`ai-fix\``;

  ensureLabel(repo, 'ai-fix', '7057ff', 'Auto-generated fix by DevOps Factory');
  ensureLabel(
    repo,
    'fix-rejected',
    'e11d48',
    'Mark a self-heal fix as wrong to lower pattern confidence'
  );

  const bodyFile = `${tmpDir}/self-heal-pr-body.md`;
  writeFileSync(bodyFile, body);
  const prUrl = sh(
    `gh pr create --repo ${repo} --head ${branch} --base ${baseBranch} --title "${title}" --body-file ${bodyFile} --label "ai-fix"`
  );
  try {
    unlinkSync(bodyFile);
  } catch {
    /* ignore */
  }

  return prUrl.match(/(https:\/\/[^\s]+)/)?.[1] || prUrl;
};

export const tryAutoMerge = (
  repo: string,
  prUrl: string,
  patternId: string | undefined,
  confidence: number
): void => {
  const prNumber = prUrl.match(/\/pull\/(\d+)/)?.[1];
  if (!prNumber) {
    console.log('  Auto-merge: could not extract PR number from URL');
    return;
  }

  const healingState = getHealingState(repo);

  if (healingState === 'discovered' || healingState === 'monitored') {
    console.log(
      `  Auto-merge: repo healingState="${healingState}" — PR #${prNumber} left for human review (auto-merge disabled)`
    );
    return;
  }

  const threshold =
    healingState === 'healing_graduated'
      ? AUTO_MERGE_GRADUATED_THRESHOLD
      : AUTO_MERGE_CONFIDENCE_THRESHOLD;

  if (confidence >= threshold) {
    console.log(
      `  Auto-merge: confidence ${confidence} >= ${threshold} [${healingState}] (pattern: ${patternId ?? 'n/a'}) — enabling auto-merge for PR #${prNumber}`
    );
    sh(`gh pr merge ${prNumber} --repo ${repo} --auto --squash`);
    notify('auto_merge', { repo, prUrl, prNumber: Number(prNumber), patternId, confidence });
  } else {
    console.log(
      `  Auto-merge: confidence ${confidence} < ${threshold} [${healingState}] (pattern: ${patternId ?? 'n/a'}) — PR #${prNumber} left for human review`
    );
  }
};

export const isDuplicateFix = (
  repo: string,
  titlePattern: string,
  changedFiles: string[] = []
): boolean => {
  try {
    const raw = sh(
      `gh pr list --repo ${repo} --state closed --limit 20 --json title,closedAt,files --label "ai-fix"`,
      120_000
    );
    if (!raw) return false;

    const closedPRs = JSON.parse(raw) as Array<{
      title: string;
      closedAt: string;
      files?: Array<{ path: string }>;
    }>;

    const now = Date.now();
    const windowMs = DEDUP_WINDOW_HOURS * 60 * 60 * 1000;

    for (const pr of closedPRs) {
      const closedTime = new Date(pr.closedAt).getTime();
      if (now - closedTime > windowMs) continue;

      if (titlePattern && pr.title.includes(titlePattern)) {
        console.log(
          `  [DEDUP] Found closed PR "${pr.title}" (closed ${Math.round((now - closedTime) / 3600000)}h ago) matching pattern "${titlePattern}"`
        );
        return true;
      }

      if (
        changedFiles.length > 0 &&
        pr.files &&
        pr.files.length > 0 &&
        pr.title.includes('AI-generated CI fix')
      ) {
        const prFilePaths = pr.files.map((f) => f.path);
        const overlap = changedFiles.filter((f) => prFilePaths.includes(f));
        if (overlap.length > 0 && overlap.length >= changedFiles.length * 0.8) {
          console.log(
            `  [DEDUP] Found closed AI-fix PR "${pr.title}" with ${overlap.length}/${changedFiles.length} overlapping files (closed ${Math.round((now - closedTime) / 3600000)}h ago)`
          );
          return true;
        }
      }
    }

    return false;
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    console.log(`  [DEDUP] Check failed (non-blocking): ${msg.slice(0, 200)}`);
    return false;
  }
};

export const createEscalationIssue = (
  repo: string,
  runId: string,
  errorSignature: string,
  previousAttempts: number
): void => {
  // Log locally instead of creating GitHub issues (reduces email noise)
  console.log(
    `[ESCALATION] ${repo} (run #${runId}): ${previousAttempts} attempts, sig: ${errorSignature.slice(0, 100)}`
  );
};

export const createIssue = (repo: string, runId: string, explanation: string): void => {
  // Log locally instead of creating GitHub issues (reduces email noise)
  console.log(`[NO-FIX] ${repo} (run #${runId}): ${explanation.slice(0, 200)}`);
};
