# DevOps-Factory: AI Code Review Template (CodeRabbit)
# REPLACED: Was using ANTHROPIC_API_KEY (incompatible with Claude Max subscription)
# Now uses CodeRabbit (free, no API key needed) for automated PR reviews
#
# Setup: Add .coderabbit.yaml to repo root (see coderabbit-config.yaml template)

name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ai-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest
    # Skip bot PRs (except ai-fix labeled)
    if: |
      github.event.pull_request.user.login != 'github-actions[bot]' ||
      contains(github.event.pull_request.labels.*.name, 'ai-fix')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR stats
        id: stats
        run: |
          DIFF=$(gh pr diff ${{ github.event.pull_request.number }} --repo ${{ github.repository }})
          LINES=$(echo "$DIFF" | wc -l)
          echo "lines=$LINES" >> $GITHUB_OUTPUT

          # Detect security-sensitive files
          SECURITY_FILES=$(echo "$DIFF" | grep -E '^\+\+\+.*\.(env|secret|key|auth|password|token|credential)' || true)
          echo "security_sensitive=$( [ -n "$SECURITY_FILES" ] && echo true || echo false )" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Security warning
        if: steps.stats.outputs.security_sensitive == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "## Security Notice

          This PR modifies security-sensitive files. Please ensure:
          - No secrets or credentials are committed
          - Environment variables are properly documented
          - Auth logic changes have been reviewed by a human

          _Detected by DevOps-Factory security scanner_"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PR size label
        run: |
          LINES=${{ steps.stats.outputs.lines }}
          if [ "$LINES" -lt 50 ]; then SIZE="XS";
          elif [ "$LINES" -lt 200 ]; then SIZE="S";
          elif [ "$LINES" -lt 500 ]; then SIZE="M";
          elif [ "$LINES" -lt 1000 ]; then SIZE="L";
          else SIZE="XL"; fi
          gh pr edit ${{ github.event.pull_request.number }} --add-label "size/$SIZE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

# NOTE: CodeRabbit reviews are triggered automatically via .coderabbit.yaml
# No API key required - CodeRabbit app handles review as a GitHub App
# Config template: templates/coderabbit-config.yaml
