# DevOps-Factory: Container Scanning (AUTO-76)
# Scans Docker images for vulnerabilities using Trivy
# Runs on PRs modifying Dockerfiles and weekly schedule

name: Container Scan

on:
  pull_request:
    branches: [main, master]
    paths: ['Dockerfile*', 'docker-compose*.yml', '.dockerignore']
  push:
    branches: [main, master]
    paths: ['Dockerfile*']
  schedule:
    - cron: '0 5 * * 6' # Weekly Saturday 5am

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find Dockerfiles
        id: find
        run: |
          FILES=$(find . -name "Dockerfile*" -not -path "*/node_modules/*" | head -5)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          COUNT=$(echo "$FILES" | grep -c . || echo "0")
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Build image for scanning
        if: steps.find.outputs.count != '0'
        run: |
          DOCKERFILE=$(echo "${{ steps.find.outputs.files }}" | head -1)
          docker build -f "$DOCKERFILE" -t scan-target:latest . 2>/dev/null || echo "Build failed - scanning Dockerfile only"

      - name: Trivy vulnerability scan
        if: steps.find.outputs.count != '0'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'scan-target:latest'
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Trivy SARIF output
        if: steps.find.outputs.count != '0'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'scan-target:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload SARIF
        if: steps.find.outputs.count != '0' && github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Parse results
        if: steps.find.outputs.count != '0'
        id: results
        run: |
          CRITICAL=$(grep -c "CRITICAL" trivy-results.txt 2>/dev/null || echo "0")
          HIGH=$(grep -c "HIGH" trivy-results.txt 2>/dev/null || echo "0")
          echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
          echo "high=$HIGH" >> $GITHUB_OUTPUT

      - name: Trivy config scan (Dockerfile best practices)
        if: steps.find.outputs.count != '0'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          output: 'trivy-config.txt'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'

      - name: Comment PR
        if: github.event_name == 'pull_request' && steps.find.outputs.count != '0'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const critical = parseInt('${{ steps.results.outputs.critical }}') || 0;
            const high = parseInt('${{ steps.results.outputs.high }}') || 0;

            const status = critical > 0 ? '🔴' : high > 0 ? '🟡' : '🟢';
            let body = `## ${status} Container Security Scan\n\n`;
            body += `| Severity | Count |\n|----------|-------|\n`;
            body += `| Critical | ${critical} |\n`;
            body += `| High | ${high} |\n`;

            try {
              const config = fs.readFileSync('trivy-config.txt', 'utf8');
              if (config.trim()) {
                body += `\n<details><summary>Dockerfile best practices</summary>\n\n\`\`\`\n${config.slice(0, 3000)}\n\`\`\`\n</details>\n`;
              }
            } catch {}

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
