name: Coverage Gate

on:
  pull_request:
    branches: [main, master]

jobs:
  coverage-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        run: pnpm vitest run --coverage --reporter=json --reporter=default

      - name: Coverage gate check
        run: |
          if [ ! -f coverage/coverage-summary.json ]; then
            echo "No coverage data found - skipping"
            exit 0
          fi

          LINES=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          BRANCHES=$(jq '.total.branches.pct' coverage/coverage-summary.json)

          echo "Lines: ${LINES}%"
          echo "Branches: ${BRANCHES}%"

          # Check baseline
          if [ -f .coverage-baseline.json ]; then
            BASELINE_LINES=$(jq '.lines' .coverage-baseline.json)
            BASELINE_BRANCHES=$(jq '.branches' .coverage-baseline.json)

            echo "Baseline - Lines: ${BASELINE_LINES}%, Branches: ${BASELINE_BRANCHES}%"

            if (( $(echo "$LINES < $BASELINE_LINES" | bc -l) )); then
              echo "::error::Coverage regression: lines ${LINES}% < baseline ${BASELINE_LINES}%"
              exit 1
            fi
          fi

          # Global threshold
          if (( $(echo "$LINES < 60" | bc -l) )); then
            echo "::warning::Lines coverage ${LINES}% below 60% threshold"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment coverage on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            if (!fs.existsSync('coverage/coverage-summary.json')) return;

            const coverage = JSON.parse(fs.readFileSync('coverage/coverage-summary.json', 'utf-8'));
            const { lines, branches, functions, statements } = coverage.total;

            let body = `## Coverage Report\n\n`;
            body += `| Metric | Coverage |\n|--------|----------|\n`;
            body += `| Lines | ${lines.pct}% |\n`;
            body += `| Branches | ${branches.pct}% |\n`;
            body += `| Functions | ${functions.pct}% |\n`;
            body += `| Statements | ${statements.pct}% |\n`;
            body += `\n> Generated by DevOps-Factory Coverage Gate`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
