# DevOps-Factory: Gitleaks Secret Scanning Template
# Scans for exposed secrets (API keys, tokens, passwords)
# Runs on PRs + weekly full scan

name: Secret Scanning

on:
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 3 * * 1' # Weekly Monday 3am UTC
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: >-
            --verbose
            --redact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
