# DevOps-Factory: k6 Load Testing Template
# Runs load tests against staging/production APIs
# Triggered manually or on release tags

name: Load Test (k6)

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Base URL to test'
        required: true
      scenario:
        description: 'Test scenario'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - load
          - stress
          - spike
  release:
    types: [published]

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine URL
        id: url
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "target=${{ github.event.inputs.target_url }}" >> $GITHUB_OUTPUT
            echo "scenario=${{ github.event.inputs.scenario }}" >> $GITHUB_OUTPUT
          else
            echo "target=${{ vars.STAGING_URL }}" >> $GITHUB_OUTPUT
            echo "scenario=smoke" >> $GITHUB_OUTPUT
          fi

      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D68
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6 -y

      - name: Create test script
        run: |
          TARGET="${{ steps.url.outputs.target }}"
          SCENARIO="${{ steps.url.outputs.scenario }}"

          cat > /tmp/load-test.js << 'SCRIPT'
          import http from 'k6/http';
          import { check, sleep } from 'k6';
          import { Rate, Trend } from 'k6/metrics';

          const errorRate = new Rate('errors');
          const responseTime = new Trend('response_time');

          const scenarios = {
            smoke: { vus: 5, duration: '1m' },
            load: { vus: 50, duration: '5m' },
            stress: { vus: 200, duration: '5m' },
            spike: {
              stages: [
                { duration: '30s', target: 10 },
                { duration: '30s', target: 200 },
                { duration: '1m', target: 200 },
                { duration: '30s', target: 10 },
              ],
            },
          };

          const scenario = __ENV.SCENARIO || 'smoke';
          const config = scenarios[scenario];

          export const options = config.stages
            ? { stages: config.stages }
            : { vus: config.vus, duration: config.duration };

          options.thresholds = {
            http_req_duration: ['p(95)<2000'],
            errors: ['rate<0.05'],
          };

          const BASE_URL = __ENV.TARGET_URL;

          export default function () {
            const endpoints = [
              '/',
              '/api/health',
            ];

            for (const endpoint of endpoints) {
              const res = http.get(`${BASE_URL}${endpoint}`);
              check(res, {
                'status is 200': (r) => r.status === 200,
                'response time < 2s': (r) => r.timings.duration < 2000,
              });
              errorRate.add(res.status !== 200);
              responseTime.add(res.timings.duration);
            }

            sleep(1);
          }
          SCRIPT

      - name: Run k6 test
        id: k6
        run: |
          k6 run /tmp/load-test.js \
            -e TARGET_URL="${{ steps.url.outputs.target }}" \
            -e SCENARIO="${{ steps.url.outputs.scenario }}" \
            --summary-export=/tmp/k6-summary.json \
            --out json=/tmp/k6-results.json 2>&1 | tee /tmp/k6-output.txt || true

      - name: Parse results
        id: results
        run: |
          if [ -f /tmp/k6-summary.json ]; then
            P95=$(jq -r '.metrics.http_req_duration.values["p(95)"] // "N/A"' /tmp/k6-summary.json)
            AVG=$(jq -r '.metrics.http_req_duration.values.avg // "N/A"' /tmp/k6-summary.json)
            REQS=$(jq -r '.metrics.http_reqs.values.count // "N/A"' /tmp/k6-summary.json)
            ERRORS=$(jq -r '.metrics.errors.values.rate // "0"' /tmp/k6-summary.json)

            echo "p95=$P95" >> $GITHUB_OUTPUT
            echo "avg=$AVG" >> $GITHUB_OUTPUT
            echo "reqs=$REQS" >> $GITHUB_OUTPUT
            echo "error_rate=$ERRORS" >> $GITHUB_OUTPUT

            # Check if thresholds passed
            FAILED=$(jq -r '.root_group.checks // [] | map(select(.fails > 0)) | length' /tmp/k6-summary.json 2>/dev/null || echo "0")
            echo "has_failures=$([[ "$FAILED" -gt 0 ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          fi

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-results-${{ steps.url.outputs.scenario }}
          path: |
            /tmp/k6-summary.json
            /tmp/k6-output.txt
          retention-days: 30

      - name: Create issue on failures
        if: steps.results.outputs.has_failures == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Load Test: Performance degradation detected (${{ steps.url.outputs.scenario }})`,
              body: [
                '## k6 Load Test Results',
                '',
                `- **Scenario**: ${{ steps.url.outputs.scenario }}`,
                `- **Target**: ${{ steps.url.outputs.target }}`,
                `- **P95 Response Time**: ${{ steps.results.outputs.p95 }}ms`,
                `- **Avg Response Time**: ${{ steps.results.outputs.avg }}ms`,
                `- **Total Requests**: ${{ steps.results.outputs.reqs }}`,
                `- **Error Rate**: ${{ steps.results.outputs.error_rate }}`,
                '',
                'Thresholds exceeded. Review the [workflow run](' +
                `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}` +
                ') for details.',
              ].join('\n'),
              labels: ['performance'],
            });
