# DevOps-Factory: PR Size Limiter (AUTO-101)
# Warns when PRs exceed size thresholds
# Encourages smaller, reviewable PRs

name: PR Size Check

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  size-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR size
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const additions = pr.additions;
            const deletions = pr.deletions;
            const total = additions + deletions;
            const files = pr.changed_files;

            // Thresholds
            const WARN_LINES = 400;
            const BLOCK_LINES = 1000;
            const WARN_FILES = 15;
            const BLOCK_FILES = 30;

            // Determine size category
            let size, emoji;
            if (total <= 50) { size = 'XS'; emoji = '🟢'; }
            else if (total <= 200) { size = 'S'; emoji = '🟢'; }
            else if (total <= WARN_LINES) { size = 'M'; emoji = '🟡'; }
            else if (total <= BLOCK_LINES) { size = 'L'; emoji = '🟠'; }
            else { size = 'XL'; emoji = '🔴'; }

            // Build comment
            let body = `## ${emoji} PR Size: **${size}** (${total} lines, ${files} files)\n\n`;

            if (total > WARN_LINES) {
              body += `| Metric | Value | Threshold |\n|--------|-------|----------|\n`;
              body += `| Total changes | ${total} | ${WARN_LINES} (warn) / ${BLOCK_LINES} (max) |\n`;
              body += `| Files changed | ${files} | ${WARN_FILES} (warn) / ${BLOCK_FILES} (max) |\n`;
              body += `| Additions | +${additions} | |\n`;
              body += `| Deletions | -${deletions} | |\n\n`;

              body += `### Tips for smaller PRs\n`;
              body += `- Split features into incremental PRs\n`;
              body += `- Separate refactoring from feature changes\n`;
              body += `- Move test additions to a dedicated PR\n`;
              body += `- Extract config/migration changes\n`;
            }

            // Only comment on large PRs to avoid noise
            if (total > WARN_LINES || files > WARN_FILES) {
              // Check for existing comment to update
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
              });

              const existing = comments.data.find(c =>
                c.user.type === 'Bot' && c.body.includes('PR Size:')
              );

              if (existing) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: existing.id,
                  body,
                });
              } else {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body,
                });
              }
            }

            // Fail on extremely large PRs (configurable)
            if (total > BLOCK_LINES && files > BLOCK_FILES) {
              core.warning(`PR is very large: ${total} lines across ${files} files. Consider splitting.`);
            }
