# DevOps-Factory: Self-Healing CI Template (Gemini-powered)
# REPLACED: Was using ANTHROPIC_API_KEY (incompatible with Claude Max subscription)
# Now uses Gemini API (free tier) for CI failure analysis and auto-fix
#
# Required secret: GEMINI_API_KEY (free at https://aistudio.google.com/apikey)

name: Self-Healing CI

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main, master]

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: self-heal-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  analyze-and-fix:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' && vars.SELF_HEAL_ENABLED == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Get failed workflow logs
        id: logs
        run: |
          RUN_ID=${{ github.event.workflow_run.id }}

          # Get failed jobs
          FAILED_JOBS=$(gh api repos/${{ github.repository }}/actions/runs/$RUN_ID/jobs \
            --jq '[.jobs[] | select(.conclusion == "failure") | .name] | join(", ")')
          echo "failed_jobs=$FAILED_JOBS" >> $GITHUB_OUTPUT

          # Download and trim logs
          gh run view $RUN_ID --log-failed --repo ${{ github.repository }} > /tmp/ci-logs.txt 2>&1 || true
          tail -400 /tmp/ci-logs.txt > /tmp/ci-logs-trimmed.txt

          # Extract error summary
          grep -iE '(error|fail|exception|cannot find|not found|unexpected)' /tmp/ci-logs.txt | head -30 > /tmp/error-summary.txt || true
          {
            echo "error_summary<<EOF"
            cat /tmp/error-summary.txt
            echo "EOF"
          } >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyze with Gemini
        id: analysis
        if: env.GEMINI_KEY != ''
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          LOGS=$(cat /tmp/ci-logs-trimmed.txt | head -c 8000)

          PROMPT="Analyze this CI failure and suggest a fix. Be concise.

          Failed jobs: ${{ steps.logs.outputs.failed_jobs }}

          Error logs:
          $LOGS

          Respond with JSON: {\"root_cause\": \"...\", \"fix_description\": \"...\", \"fix_type\": \"typescript|test|lint|dependency|config|unknown\", \"confidence\": 0.0-1.0}"

          RESPONSE=$(curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$GEMINI_KEY" \
            -H 'Content-Type: application/json' \
            -d "$(jq -n --arg p "$PROMPT" '{contents: [{parts: [{text: $p}]}]}')")

          echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text' > /tmp/analysis.txt

          CONFIDENCE=$(jq -r '.confidence // 0' /tmp/analysis.txt 2>/dev/null || echo "0")
          echo "confidence=$CONFIDENCE" >> $GITHUB_OUTPUT

          FIX_TYPE=$(jq -r '.fix_type // "unknown"' /tmp/analysis.txt 2>/dev/null || echo "unknown")
          echo "fix_type=$FIX_TYPE" >> $GITHUB_OUTPUT

      - name: Create diagnostic issue
        run: |
          ANALYSIS=""
          if [ -f /tmp/analysis.txt ]; then
            ANALYSIS=$(cat /tmp/analysis.txt)
          fi

          gh issue create \
            --title "CI failure: ${{ steps.logs.outputs.failed_jobs }}" \
            --body "$(cat <<EOF
          ## CI Failure Analysis

          **Failed run**: ${{ github.event.workflow_run.html_url }}
          **Failed jobs**: ${{ steps.logs.outputs.failed_jobs }}
          **Branch**: ${{ github.event.workflow_run.head_branch }}

          ### Error Summary
          \`\`\`
          ${{ steps.logs.outputs.error_summary }}
          \`\`\`

          ### AI Analysis
          $ANALYSIS

          ---
          _Generated by DevOps-Factory self-healing (Gemini)_
          EOF
          )" \
            --label "bug,ai-analysis"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
