# DevOps-Factory: Self-Healing CI Template
# Triggered when CI fails on main/master - analyzes logs and creates a fix PR
# Uses Claude Sonnet for code analysis and fix generation

name: Self-Healing CI

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main, master]

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  analyze-and-fix:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Get failed workflow logs
        id: logs
        run: |
          RUN_ID=${{ github.event.workflow_run.id }}

          # Get failed jobs
          JOBS=$(gh api repos/${{ github.repository }}/actions/runs/$RUN_ID/jobs --jq '.jobs[] | select(.conclusion == "failure")')

          # Get logs for failed jobs
          FAILED_JOBS=$(echo "$JOBS" | jq -r '.name')
          echo "failed_jobs=$FAILED_JOBS" >> $GITHUB_OUTPUT

          # Download logs
          gh run view $RUN_ID --log-failed --repo ${{ github.repository }} > /tmp/ci-logs.txt 2>&1 || true

          # Trim to last 200 lines per job (avoid token bloat)
          tail -600 /tmp/ci-logs.txt > /tmp/ci-logs-trimmed.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create fix branch
        id: branch
        run: |
          BRANCH="ai-fix/ci-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Claude Fix
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: claude-sonnet-4-5-20250929
          direct_prompt: |
            The CI pipeline has failed. Analyze the error logs below and fix the issue.

            ## Failed jobs
            ${{ steps.logs.outputs.failed_jobs }}

            ## Error logs (last 600 lines)
            $(cat /tmp/ci-logs-trimmed.txt)

            ## Instructions
            1. Identify the root cause of the CI failure
            2. Make the minimal fix needed to resolve it
            3. Do NOT make unrelated changes
            4. If the fix requires a dependency update, update package.json/lockfile
            5. If you cannot determine the fix with confidence, create a detailed issue instead

            Common CI failures:
            - TypeScript errors: fix type issues
            - Test failures: fix the test or the code it tests
            - Lint errors: fix the lint violations
            - Build errors: fix import/export issues
            - Dependency issues: update or pin versions
          timeout_minutes: 15
          allowed_tools: "Edit,Write,Read,Glob,Grep,Bash"

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and create PR
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config user.name "DevOps Factory Bot"
          git config user.email "devops-factory[bot]@users.noreply.github.com"
          git add -A
          git commit -m "fix(ci): auto-fix CI failure

          Failed workflow: ${{ github.event.workflow_run.name }}
          Run: ${{ github.event.workflow_run.html_url }}

          Co-Authored-By: Claude Sonnet <noreply@anthropic.com>"

          git push origin ${{ steps.branch.outputs.branch }}

          gh pr create \
            --title "fix(ci): Auto-fix CI failure" \
            --body "$(cat <<'EOF'
          ## Auto-Fix PR

          **Triggered by**: CI failure on `${{ github.event.workflow_run.head_branch }}`
          **Failed run**: ${{ github.event.workflow_run.html_url }}
          **Failed jobs**: ${{ steps.logs.outputs.failed_jobs }}

          This PR was automatically generated by DevOps-Factory self-healing.
          Please review the changes before merging.

          > Generated by AI - review carefully before merge

          EOF
          )" \
            --label "ai-fix" \
            --head "${{ steps.branch.outputs.branch }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue if no fix found
        if: steps.changes.outputs.has_changes == 'false'
        run: |
          gh issue create \
            --title "CI failure needs manual investigation" \
            --body "$(cat <<'EOF'
          ## CI Failure - Manual Investigation Needed

          **Failed run**: ${{ github.event.workflow_run.html_url }}
          **Failed jobs**: ${{ steps.logs.outputs.failed_jobs }}

          Self-healing could not determine a fix automatically.
          Please investigate the failed workflow run.

          EOF
          )" \
            --label "bug,needs-triage"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
