# DevOps-Factory: SSL Certificate Expiration Check
# Centralized - runs from DevOps-Factory repo
# Alerts 30 days before certificate expiry

name: SSL Certificate Check

on:
  schedule:
    - cron: '0 6 * * 1' # Weekly Monday 6am UTC
  workflow_dispatch:

permissions:
  issues: write

jobs:
  check-ssl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Site Au-marais
            domain: au-marais.fr
          - name: Livret Au-Marais
            domain: livret.au-marais.fr

    steps:
      - name: Check SSL for ${{ matrix.name }}
        id: ssl
        run: |
          DOMAIN="${{ matrix.domain }}"
          EXPIRY=$(echo | openssl s_client -servername "$DOMAIN" -connect "$DOMAIN:443" 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)

          if [ -z "$EXPIRY" ]; then
            echo "days_left=-1" >> $GITHUB_OUTPUT
            echo "expiry=UNKNOWN" >> $GITHUB_OUTPUT
            echo "alert=true" >> $GITHUB_OUTPUT
          else
            EXPIRY_EPOCH=$(date -d "$EXPIRY" +%s)
            NOW_EPOCH=$(date +%s)
            DAYS_LEFT=$(( (EXPIRY_EPOCH - NOW_EPOCH) / 86400 ))
            echo "days_left=$DAYS_LEFT" >> $GITHUB_OUTPUT
            echo "expiry=$EXPIRY" >> $GITHUB_OUTPUT

            if [ "$DAYS_LEFT" -lt 30 ]; then
              echo "alert=true" >> $GITHUB_OUTPUT
            else
              echo "alert=false" >> $GITHUB_OUTPUT
            fi
          fi

          echo "${{ matrix.name }} ($DOMAIN): ${DAYS_LEFT:-?} days left (expires: ${EXPIRY:-unknown})"

      - name: Create alert issue
        if: steps.ssl.outputs.alert == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const daysLeft = parseInt('${{ steps.ssl.outputs.days_left }}');
            const label = daysLeft < 7 ? 'urgent' : 'warning';
            const title = `SSL: ${{ matrix.name }} expires in ${daysLeft} days`;

            const existing = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'ssl',
              per_page: 10,
            });

            if (existing.data.some(i => i.title.includes('${{ matrix.name }}'))) return;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body: [
                '## SSL Certificate Expiring Soon',
                '',
                `- **Site**: ${{ matrix.name }}`,
                `- **Domain**: ${{ matrix.domain }}`,
                `- **Expires**: ${{ steps.ssl.outputs.expiry }}`,
                `- **Days left**: ${daysLeft}`,
                '',
                daysLeft < 7 ? '**URGENT: Renew immediately!**' : 'Please renew before expiry.',
              ].join('\n'),
              labels: ['ssl', label],
            });
