# DevOps-Factory: TypeDoc Documentation Generator
# Auto-generates TypeScript API documentation on push to main
# Publishes to GitHub Pages under /docs/

name: TypeDoc Generation

on:
  push:
    branches: [main, master]
    paths:
      - 'src/**'
      - 'lib/**'
      - 'tsconfig.json'
      - 'typedoc.json'
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  typedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect package manager
        id: detect
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "manager=pnpm" >> $GITHUB_OUTPUT
            echo "install=pnpm install --frozen-lockfile" >> $GITHUB_OUTPUT
          elif [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "install=yarn install --frozen-lockfile" >> $GITHUB_OUTPUT
          else
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "install=npm ci" >> $GITHUB_OUTPUT
          fi

      - uses: pnpm/action-setup@v4
        if: steps.detect.outputs.manager == 'pnpm'
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: ${{ steps.detect.outputs.manager }}

      - name: Install dependencies
        run: ${{ steps.detect.outputs.install }}

      - name: Install TypeDoc
        run: npm install -g typedoc

      - name: Generate docs
        run: |
          # Use project typedoc.json if exists, else sensible defaults
          if [ -f "typedoc.json" ]; then
            typedoc
          else
            typedoc --entryPoints src/index.ts --out docs \
              --plugin typedoc-plugin-markdown \
              --exclude "**/*.test.ts" \
              --exclude "**/*.spec.ts" \
              --exclude "**/node_modules/**" \
              --skipErrorChecking \
              2>/dev/null || \
            typedoc --entryPointStrategy expand --entryPoints src --out docs \
              --exclude "**/*.test.ts" \
              --exclude "**/*.spec.ts" \
              --exclude "**/node_modules/**" \
              --skipErrorChecking
          fi

      - name: Commit docs
        if: github.event_name == 'push'
        run: |
          git config user.name "DevOps Factory Bot"
          git config user.email "devops-factory[bot]@users.noreply.github.com"
          git add docs/ || true
          git diff --cached --quiet || git commit -m "docs: auto-generate TypeDoc documentation"
          git push || true
