# DevOps-Factory: Uptime Monitoring (centralized)
# Runs every 5 minutes from DevOps-Factory repo
# Checks all production URLs and creates issues on failure

name: Uptime Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  check-uptime:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Site Au-marais
            url: https://au-marais.fr
          - name: Livret Au-Marais
            url: https://livret.au-marais.fr

    steps:
      - name: Check ${{ matrix.name }}
        id: check
        run: |
          URL="${{ matrix.url }}"
          START=$(date +%s%N)
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 "$URL" || echo "000")
          END=$(date +%s%N)
          DURATION=$(( (END - START) / 1000000 ))

          echo "status=$STATUS" >> $GITHUB_OUTPUT
          echo "duration=$DURATION" >> $GITHUB_OUTPUT
          echo "${{ matrix.name }}: HTTP $STATUS (${DURATION}ms)"

          if [ "$STATUS" != "200" ]; then
            echo "is_down=true" >> $GITHUB_OUTPUT
          else
            echo "is_down=false" >> $GITHUB_OUTPUT
          fi

      - name: Create issue if down
        if: steps.check.outputs.is_down == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const title = `DOWNTIME: ${{ matrix.name }} is down (HTTP ${{ steps.check.outputs.status }})`;

            // Check if issue already exists (avoid duplicates)
            const existing = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'downtime',
              per_page: 10,
            });

            const duplicate = existing.data.find(i =>
              i.title.includes('${{ matrix.name }}')
            );

            if (duplicate) {
              // Add comment to existing issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: duplicate.number,
                body: `Still down at ${new Date().toISOString()} - HTTP ${{ steps.check.outputs.status }} (${{ steps.check.outputs.duration }}ms)`,
              });
            } else {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title,
                body: [
                  '## Site Down Alert',
                  '',
                  `- **Site**: ${{ matrix.name }}`,
                  `- **URL**: ${{ matrix.url }}`,
                  `- **Status**: HTTP ${{ steps.check.outputs.status }}`,
                  `- **Response time**: ${{ steps.check.outputs.duration }}ms`,
                  `- **Detected**: ${new Date().toISOString()}`,
                  '',
                  'Please investigate immediately.',
                ].join('\n'),
                labels: ['downtime', 'urgent'],
              });
            }

      - name: Auto-close if recovered
        if: steps.check.outputs.is_down == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'downtime',
              per_page: 10,
            });

            const downtimeIssue = issues.data.find(i =>
              i.title.includes('${{ matrix.name }}')
            );

            if (downtimeIssue) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: downtimeIssue.number,
                body: `Site recovered at ${new Date().toISOString()} - HTTP ${{ steps.check.outputs.status }} (${{ steps.check.outputs.duration }}ms)`,
              });
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: downtimeIssue.number,
                state: 'closed',
              });
            }
