/**
 * redeploy-templates.ts
 *
 * Re-deploys improved templates to repos that have the old broken versions.
 * Only updates repos where the workflow exists AND differs from the new template.
 *
 * Usage: pnpm redeploy-templates -- --template semgrep --dry-run
 *        pnpm redeploy-templates -- --template all
 */

import { execSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { KNOWN_PROJECTS } from '../factory.config.js';

const TEMPLATES: Record<string, { file: string; target: string; stacks?: string[] }> = {
  semgrep: {
    file: 'templates/semgrep.yml',
    target: '.github/workflows/semgrep.yml',
  },
  'coverage-tracking': {
    file: 'templates/coverage-tracking.yml',
    target: '.github/workflows/coverage-tracking.yml',
    stacks: ['nextjs', 'fastify', 'node', 'astro'],
  },
  'auto-merge-deps': {
    file: 'templates/auto-merge-deps.yml',
    target: '.github/workflows/auto-merge-deps.yml',
  },
};

const sh = (cmd: string): string => {
  try {
    return execSync(cmd, { encoding: 'utf-8', timeout: 30000 }).trim();
  } catch {
    return '';
  }
};

const getRemoteFileContent = (repo: string, path: string): string | null => {
  const result = sh(`gh api "repos/${repo}/contents/${path}" --jq ".content" 2>/dev/null`);
  if (!result) return null;
  try {
    return Buffer.from(result.replace(/\n/g, ''), 'base64').toString('utf-8');
  } catch {
    return null;
  }
};

const createUpdatePR = (
  repo: string,
  targetPath: string,
  content: string,
  templateName: string
): string | null => {
  const branch = `devops-factory/update-${templateName}-${Date.now()}`;

  // Get default branch SHA
  const defaultBranch = sh(`gh api "repos/${repo}" --jq ".default_branch"`) || 'main';
  const sha = sh(`gh api "repos/${repo}/git/ref/heads/${defaultBranch}" --jq ".object.sha"`);
  if (!sha) return null;

  // Create branch
  const branchResult = sh(
    `gh api "repos/${repo}/git/refs" -f ref="refs/heads/${branch}" -f sha="${sha}"`
  );
  if (!branchResult.includes(branch)) return null;

  // Get existing file SHA (needed for update)
  const fileSha = sh(
    `gh api "repos/${repo}/contents/${targetPath}?ref=${defaultBranch}" --jq ".sha" 2>/dev/null`
  );

  // Upload file
  const encodedContent = Buffer.from(content).toString('base64');
  const uploadPayload = JSON.stringify({
    message: `chore: update ${templateName} workflow (DevOps-Factory)`,
    content: encodedContent,
    branch,
    ...(fileSha ? { sha: fileSha } : {}),
  });

  const tmpFile = `/tmp/redeploy-${Date.now()}.json`;
  execSync(`cat > ${tmpFile} << 'PAYLOAD_EOF'\n${uploadPayload}\nPAYLOAD_EOF`, {
    encoding: 'utf-8',
  });

  const uploadResult = sh(
    `gh api "repos/${repo}/contents/${targetPath}" -X PUT --input ${tmpFile}`
  );
  try {
    execSync(`rm -f ${tmpFile}`);
  } catch {
    /* ignore */
  }

  if (!uploadResult.includes('content')) return null;

  // Create PR
  const prUrl = sh(
    `gh pr create --repo ${repo} --head ${branch} --base ${defaultBranch} ` +
      `--title "chore: update ${templateName} workflow" ` +
      `--body "Updated ${templateName} workflow template from DevOps-Factory.\n\nChanges:\n- Stack-aware configuration\n- Non-blocking mode (findings reported but don't fail CI)\n- Better error handling\n\n*Auto-generated by DevOps-Factory*" ` +
      `--label "devops-factory"`
  );

  return prUrl.match(/(https:\/\/[^\s]+)/)?.[1] || null;
};

const main = () => {
  const args = process.argv.slice(2);
  let templateName = '';
  let dryRun = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--template' && args[i + 1]) templateName = args[i + 1];
    if (args[i] === '--dry-run') dryRun = true;
  }

  if (!templateName) {
    console.error('Usage: pnpm redeploy-templates -- --template <name|all> [--dry-run]');
    console.error(`Available: ${Object.keys(TEMPLATES).join(', ')}, all`);
    process.exit(1);
  }

  const templatesToProcess =
    templateName === 'all'
      ? Object.entries(TEMPLATES)
      : TEMPLATES[templateName]
        ? [[templateName, TEMPLATES[templateName]] as [string, (typeof TEMPLATES)[string]]]
        : [];

  if (templatesToProcess.length === 0) {
    console.error(`Unknown template: ${templateName}`);
    process.exit(1);
  }

  for (const [name, config] of templatesToProcess) {
    console.log(`\n=== Template: ${name} ===`);
    const localContent = readFileSync(config.file, 'utf-8');

    const eligibleProjects = KNOWN_PROJECTS.filter((p) => {
      if (p.hidden) return false;
      if (config.stacks && !config.stacks.includes(p.stack)) return false;
      return true;
    });

    let updated = 0;
    let skipped = 0;
    let created = 0;

    for (const project of eligibleProjects) {
      process.stdout.write(`  ${project.name}... `);

      const remoteContent = getRemoteFileContent(project.repo, config.target);

      if (!remoteContent) {
        console.log('not found (skip)');
        skipped++;
        continue;
      }

      // Normalize for comparison
      const normalizeWf = (s: string) => s.replace(/\r\n/g, '\n').trim();
      if (normalizeWf(remoteContent) === normalizeWf(localContent)) {
        console.log('up to date');
        skipped++;
        continue;
      }

      if (dryRun) {
        console.log('NEEDS UPDATE (dry-run)');
        updated++;
        continue;
      }

      const prUrl = createUpdatePR(project.repo, config.target, localContent, name);
      if (prUrl) {
        console.log(`PR: ${prUrl}`);
        created++;
      } else {
        console.log('FAILED to create PR');
      }
      updated++;
    }

    console.log(`\n  Summary: ${updated} need update, ${skipped} skipped, ${created} PRs created`);
  }
};

main();
